export const TAROT_PAGE_COPY_OVERRIDE = {
  'zh-CN': {
    locale: 'zh-CN',
    back: '返回',
    close: '关闭',
    search: '搜索',
    tabs: [
      { key: 'card', label: '牌阵' },
      { key: 'astro', label: '星图' },
      { key: 'fate', label: '缘分' },
      { key: 'birth', label: '生命' },
      { key: 'chat', label: '聊天' },
    ],
    quickConsults: [
      {
        title: '爱情提问',
        icon: '💞',
        desc: '恋人关系 / 复合 / 婚姻',
        spreadCode: 'LOVE_TRIAD',
        spreadTitle: '爱情三角阵',
      },
      {
        title: '事业学业',
        icon: '🎯',
        desc: '工作发展 / 晋升 / 方向',
        spreadCode: 'PAST_PRESENT_FUTURE',
        spreadTitle: '时间之流',
      },
      {
        title: '财富启示',
        icon: '💰',
        desc: '财务 / 投资 / 规划',
        spreadCode: 'SINGLE',
        spreadTitle: '单牌占卜',
      },
    ],
    beginnerSpreads: [
      {
        title: '单牌',
        desc: '快速指引',
        code: 'SINGLE',
        badge: '免费',
        badgeTone: 'free',
        icon: '🃏',
        cost: 0,
      },
      {
        title: '三牌阵',
        desc: '过去 / 现在 / 未来',
        code: 'PAST_PRESENT_FUTURE',
        badge: '免费',
        badgeTone: 'free',
        icon: '🔮',
        cost: 0,
      },
      {
        title: '恋人阵',
        desc: '感情分析',
        code: 'LOVE_TRIAD',
        badge: '热门',
        badgeTone: 'hot',
        icon: '❤️',
        cost: 0,
      },
      {
        title: '权杖二',
        desc: '关系观望',
        code: 'WANDS_TWO',
        badge: '免费',
        badgeTone: 'free',
        icon: '🪄',
        cost: 0,
      },
      {
        title: '圣杯骑士',
        desc: '情感消息',
        code: 'CUPS_KNIGHT',
        badge: '免费',
        badgeTone: 'free',
        icon: '🥂',
        cost: 0,
      },
      {
        title: '宝剑三',
        desc: '情绪疗愈',
        code: 'SWORDS_THREE',
        badge: '免费',
        badgeTone: 'free',
        icon: '⚔️',
        cost: 0,
      },
    ],
    advancedSpreads: [
      {
        title: '凯尔特十字',
        desc: '深度解读',
        code: 'CELTIC_CROSS',
        badge: '经典',
        badgeTone: 'classic',
        icon: '✴️',
        cost: 20,
      },
      {
        title: '马赛十字',
        desc: '多角度分析',
        code: 'MARSEILLE_CROSS',
        badge: '专业',
        badgeTone: 'pro',
        icon: '✝️',
        cost: 30,
      },
      {
        title: '命运之轮',
        desc: '周期趋势',
        code: 'WHEEL_OF_FORTUNE',
        badge: '专业',
        badgeTone: 'pro',
        icon: '🎡',
        cost: 30,
      },
      {
        title: '双柱六星',
        desc: '年度规划',
        code: 'TWO_PILLARS_SIX_STARS',
        badge: '专业',
        badgeTone: 'pro',
        icon: '✨',
        cost: 50,
      },
      {
        title: '星盘全息',
        desc: '全局洞察',
        code: 'ASTRO_HOLOGRAM',
        badge: '专业',
        badgeTone: 'pro',
        icon: '🌌',
        cost: 50,
      },
      {
        title: '神圣时间线',
        desc: '关键节点',
        code: 'SACRED_TIMELINE',
        badge: '专业',
        badgeTone: 'pro',
        icon: '⏳',
        cost: 50,
      },
    ],
    banners: [
      {
        id: 1,
        title: '每日一牌',
        subtitle: '开启今日能量指引',
        gradient: 'from-[#7f2416] via-[#b84e2b] to-[#d6b77a]',
        icon: '🃏',
      },
      {
        id: 2,
        title: '爱情塔罗',
        subtitle: '解读你的情感密码',
        gradient: 'from-[#6a1f17] via-[#9d4124] to-[#d0a85b]',
        icon: '💖',
      },
      {
        id: 3,
        title: '事业指引',
        subtitle: '为下一步行动做全局观察',
        gradient: 'from-[#3f1e17] via-[#7a3218] to-[#c79548]',
        icon: '🎯',
      },
    ],
    defaultSpreadTitle: '塔罗占卜',
    dailyFallbackTitle: '今日之牌',
    unknownCard: '未知牌',
    upright: '正位',
    reversed: '逆位',
    share: '分享',
    shareSuccess: '分享文案已复制',
    shareFailed: '分享失败，请稍后重试',
    enterQuestion: '请输入你的问题',
    insufficientPoints: (cost, credits) =>
      `积分不足，该牌阵需要 ${cost} 积分，当前余额：${credits}`,
    insufficientPointsGuest: (cost) => `积分不足，该牌阵需要 ${cost} 积分`,
    spendSuccess: (cost) => `已消耗 ${cost} 积分`,
    spendFailed: '积分扣除失败',
    noTarotData: '未获取到塔罗牌数据',
    drawSuccess: '抽牌成功',
    drawFailed: '抽取塔罗牌失败',
    aiInsufficientPoints: (cost, credits) =>
      `积分不足，AI 解读需要 ${cost} 积分，当前余额：${credits}`,
    aiInsufficientPointsGuest: (cost) => `积分不足，AI 解读需要 ${cost} 积分`,
    aiFailed: 'AI 解读失败，请稍后重试',
    aiGenerationFailed: '生成报告失败',
    needDrawFirst: '请先抽牌',
    recordSaved: '记录已保存',
    saveFailed: '保存记录失败',
    favoriteSaved: '已加入收藏',
    favoriteRemoved: '已取消收藏',
    favoriteFailed: '收藏操作失败',
    loginFirst: '请先登录',
    comingSoon: '该牌阵即将上线，敬请期待',
    modalHint: '静下心来，专注于你真正想问的问题。',
    costHint: (cost) => `需要消耗 ${cost} 积分`,
    questionPlaceholder: '请输入你想占卜的问题，例如：我的感情接下来会怎样？',
    drawLoading: '抽牌中...',
    drawButton: '开始抽牌',
    resultTitle: '抽牌结果',
    aiInterpret: 'AI 解读',
    favorite: '收藏',
    saveRecord: '保存记录',
    spreadSpendLabel: (spreadTitle) => `塔罗占卜 - ${spreadTitle}`,
    aiSpendLabel: 'AI塔罗解读',
    creditUnitCompact: '积分',
    todayButton: '查看今日牌卡',
    drawNow: '立即抽取',
    beginnerTitle: '入门牌阵',
    beginnerBadge: '免费',
    advancedTitle: '进阶牌阵',
    advancedBadge: '积分兑换',
    more: '更多',
    currentPoints: '当前积分：',
    getMorePoints: '获取更多积分 →',
    promptIntro: '你是一位专业的塔罗牌解读师，请为用户解读以下塔罗牌阵。',
    promptRulesTitle: '【格式要求】',
    promptRules: [
      '仅输出纯文本，不使用 Markdown 或富文本格式。',
      '不要使用标题、代码块、链接语法或花哨符号。',
      '使用自然段落与换行组织内容，必要时用数字序号。',
    ],
    promptInfoTitle: '【占卜信息】',
    promptQuestionLabel: '用户问题：',
    promptCardsLabel: '抽到的牌：',
    promptRequestTitle: '【解读要求】',
    promptRequests: [
      '1. 先概括整个牌阵的能量与主题。',
      '2. 逐张解释每张牌在当前位置的含义，以及正逆位的影响。',
      '3. 分析牌与牌之间的关系，以及它们共同构成的故事线。',
      '4. 直接回答用户的问题。',
      '5. 给出具体、可执行的建议。',
      '6. 如适合，可给出宽泛的时间参考。',
    ],
    promptClosing: '请用温暖、有洞察力的语气，帮助用户获得更清晰的方向。',
  },
  'en-US': {
    locale: 'en-US',
    back: 'Back',
    close: 'Close',
    search: 'Search',
    tabs: [
      { key: 'card', label: 'Cards' },
      { key: 'astro', label: 'Stars' },
      { key: 'fate', label: 'Fate' },
      { key: 'birth', label: 'Life' },
      { key: 'chat', label: 'Chat' },
    ],
    quickConsults: [
      {
        title: 'Love Reading',
        icon: '💞',
        desc: 'Relationship / reunion / marriage',
        spreadCode: 'LOVE_TRIAD',
        spreadTitle: 'Love Triangle Spread',
      },
      {
        title: 'Career & Study',
        icon: '🎯',
        desc: 'Work growth / promotion / direction',
        spreadCode: 'PAST_PRESENT_FUTURE',
        spreadTitle: 'Flow of Time',
      },
      {
        title: 'Wealth Insight',
        icon: '💰',
        desc: 'Money / investment / planning',
        spreadCode: 'SINGLE',
        spreadTitle: 'Single Card Reading',
      },
    ],
    beginnerSpreads: [
      {
        title: 'Single Card',
        desc: 'Quick guidance',
        code: 'SINGLE',
        badge: 'Free',
        badgeTone: 'free',
        icon: '🃏',
        cost: 0,
      },
      {
        title: 'Three Cards',
        desc: 'Past / Present / Future',
        code: 'PAST_PRESENT_FUTURE',
        badge: 'Free',
        badgeTone: 'free',
        icon: '🔮',
        cost: 0,
      },
      {
        title: 'Love Spread',
        desc: 'Relationship analysis',
        code: 'LOVE_TRIAD',
        badge: 'Hot',
        badgeTone: 'hot',
        icon: '❤️',
        cost: 0,
      },
      {
        title: 'Two of Wands',
        desc: 'Relationship outlook',
        code: 'WANDS_TWO',
        badge: 'Free',
        badgeTone: 'free',
        icon: '🪄',
        cost: 0,
      },
      {
        title: 'Knight of Cups',
        desc: 'Emotional message',
        code: 'CUPS_KNIGHT',
        badge: 'Free',
        badgeTone: 'free',
        icon: '🥂',
        cost: 0,
      },
      {
        title: 'Three of Swords',
        desc: 'Emotional healing',
        code: 'SWORDS_THREE',
        badge: 'Free',
        badgeTone: 'free',
        icon: '⚔️',
        cost: 0,
      },
    ],
    advancedSpreads: [
      {
        title: 'Celtic Cross',
        desc: 'Deep interpretation',
        code: 'CELTIC_CROSS',
        badge: 'Classic',
        badgeTone: 'classic',
        icon: '✴️',
        cost: 20,
      },
      {
        title: 'Marseille Cross',
        desc: 'Multi-angle analysis',
        code: 'MARSEILLE_CROSS',
        badge: 'Pro',
        badgeTone: 'pro',
        icon: '✝️',
        cost: 30,
      },
      {
        title: 'Wheel of Fortune',
        desc: 'Cycle forecast',
        code: 'WHEEL_OF_FORTUNE',
        badge: 'Pro',
        badgeTone: 'pro',
        icon: '🎡',
        cost: 30,
      },
      {
        title: 'Two Pillars Six Stars',
        desc: 'Annual planning',
        code: 'TWO_PILLARS_SIX_STARS',
        badge: 'Pro',
        badgeTone: 'pro',
        icon: '✨',
        cost: 50,
      },
      {
        title: 'Astro Hologram',
        desc: 'Big-picture insight',
        code: 'ASTRO_HOLOGRAM',
        badge: 'Pro',
        badgeTone: 'pro',
        icon: '🌌',
        cost: 50,
      },
      {
        title: 'Sacred Timeline',
        desc: 'Key moments',
        code: 'SACRED_TIMELINE',
        badge: 'Pro',
        badgeTone: 'pro',
        icon: '⏳',
        cost: 50,
      },
    ],
    banners: [
      {
        id: 1,
        title: 'Daily Card',
        subtitle: "Open today's energetic guidance",
        gradient: 'from-[#7f2416] via-[#b84e2b] to-[#d6b77a]',
        icon: '🃏',
      },
      {
        id: 2,
        title: 'Love Tarot',
        subtitle: 'Decode your relationship energy',
        gradient: 'from-[#6a1f17] via-[#9d4124] to-[#d0a85b]',
        icon: '💖',
      },
      {
        id: 3,
        title: 'Career Guidance',
        subtitle: 'A wider reading for your next move',
        gradient: 'from-[#3f1e17] via-[#7a3218] to-[#c79548]',
        icon: '🎯',
      },
    ],
    defaultSpreadTitle: 'Tarot Reading',
    dailyFallbackTitle: "Today's Card",
    unknownCard: 'Unknown Card',
    upright: 'Upright',
    reversed: 'Reversed',
    share: 'Share',
    shareSuccess: 'Share text copied',
    shareFailed: 'Sharing failed. Please try again later.',
    enterQuestion: 'Please enter your question',
    insufficientPoints: (cost, credits) =>
      `Not enough credits. This spread needs ${cost} credits, current balance: ${credits}`,
    insufficientPointsGuest: (cost) =>
      `Not enough credits. This spread needs ${cost} credits.`,
    spendSuccess: (cost) => `Spent ${cost} credits`,
    spendFailed: 'Failed to deduct credits',
    noTarotData: 'No Tarot card data was returned',
    drawSuccess: 'Cards drawn successfully!',
    drawFailed: 'Failed to draw Tarot cards',
    aiInsufficientPoints: (cost, credits) =>
      `Not enough credits. AI reading needs ${cost} credits, current balance: ${credits}`,
    aiInsufficientPointsGuest: (cost) =>
      `Not enough credits. AI reading needs ${cost} credits.`,
    aiFailed: 'AI reading failed. Please try again later.',
    aiGenerationFailed: 'Failed to generate the report',
    needDrawFirst: 'Please draw cards first',
    recordSaved: 'Record saved',
    saveFailed: 'Failed to save record',
    favoriteSaved: 'Added to favorites',
    favoriteRemoved: 'Removed from favorites',
    favoriteFailed: 'Favorite action failed',
    loginFirst: 'Please sign in first',
    comingSoon: 'This spread is coming soon',
    modalHint: 'Center yourself and focus on what you truly want to ask.',
    costHint: (cost) => `${cost} credits required`,
    questionPlaceholder:
      'Enter the question you want to explore, for example: How is my love life unfolding?',
    drawLoading: 'Drawing...',
    drawButton: 'Draw Cards',
    resultTitle: 'Draw Result',
    aiInterpret: 'AI Reading',
    favorite: 'Favorite',
    saveRecord: 'Save Record',
    spreadSpendLabel: (spreadTitle) => `Tarot spread - ${spreadTitle}`,
    aiSpendLabel: 'AI Tarot reading',
    creditUnitCompact: ' cr',
    todayButton: "View today's card",
    drawNow: 'Draw now',
    beginnerTitle: 'Starter Spreads',
    beginnerBadge: 'Free',
    advancedTitle: 'Advanced Spreads',
    advancedBadge: 'Credits',
    more: 'More',
    currentPoints: 'Current credits: ',
    getMorePoints: 'Get more credits →',
    promptIntro:
      'You are a professional Tarot reader. Please interpret the following Tarot spread for the user.',
    promptRulesTitle: '[Formatting Requirements]',
    promptRules: [
      'Reply in plain text only. Do not use Markdown or rich-text formatting.',
      'Do not use headings, code fences, link syntax, or decorative symbols in the answer.',
      'Use natural paragraphs and line breaks. Use numbered sections if needed.',
    ],
    promptInfoTitle: '[Reading Information]',
    promptQuestionLabel: 'User question:',
    promptCardsLabel: 'Drawn cards:',
    promptRequestTitle: '[Interpretation Requests]',
    promptRequests: [
      '1. Give an overview of the spread energy and theme.',
      '2. Explain each card in its current position, including upright or reversed meaning.',
      '3. Describe the relationship between the cards and the larger story they form.',
      '4. Answer the user question directly.',
      '5. Offer practical and specific advice.',
      '6. If appropriate, include a broad timing reference.',
    ],
    promptClosing:
      'Use a warm and insightful tone that helps the user find clarity.',
  },
}

export function getTarotPageCopyOverride(locale) {
  return TAROT_PAGE_COPY_OVERRIDE[locale] || TAROT_PAGE_COPY_OVERRIDE['zh-CN']
}
